/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TradingPostImport } from './routes/TradingPost'
import { Route as SignInImport } from './routes/SignIn'
import { Route as HomeImport } from './routes/Home'
import { Route as AccountImport } from './routes/Account'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TradingPostRoute = TradingPostImport.update({
  path: '/TradingPost',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  path: '/SignIn',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  path: '/Home',
  getParentRoute: () => rootRoute,
} as any)

const AccountRoute = AccountImport.update({
  path: '/Account',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Account': {
      id: '/Account'
      path: '/Account'
      fullPath: '/Account'
      preLoaderRoute: typeof AccountImport
      parentRoute: typeof rootRoute
    }
    '/Home': {
      id: '/Home'
      path: '/Home'
      fullPath: '/Home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/SignIn': {
      id: '/SignIn'
      path: '/SignIn'
      fullPath: '/SignIn'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/TradingPost': {
      id: '/TradingPost'
      path: '/TradingPost'
      fullPath: '/TradingPost'
      preLoaderRoute: typeof TradingPostImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Account': typeof AccountRoute
  '/Home': typeof HomeRoute
  '/SignIn': typeof SignInRoute
  '/TradingPost': typeof TradingPostRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Account': typeof AccountRoute
  '/Home': typeof HomeRoute
  '/SignIn': typeof SignInRoute
  '/TradingPost': typeof TradingPostRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Account': typeof AccountRoute
  '/Home': typeof HomeRoute
  '/SignIn': typeof SignInRoute
  '/TradingPost': typeof TradingPostRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Account' | '/Home' | '/SignIn' | '/TradingPost'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Account' | '/Home' | '/SignIn' | '/TradingPost'
  id: '__root__' | '/' | '/Account' | '/Home' | '/SignIn' | '/TradingPost'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  HomeRoute: typeof HomeRoute
  SignInRoute: typeof SignInRoute
  TradingPostRoute: typeof TradingPostRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  HomeRoute: HomeRoute,
  SignInRoute: SignInRoute,
  TradingPostRoute: TradingPostRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Account",
        "/Home",
        "/SignIn",
        "/TradingPost"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Account": {
      "filePath": "Account.tsx"
    },
    "/Home": {
      "filePath": "Home.tsx"
    },
    "/SignIn": {
      "filePath": "SignIn.tsx"
    },
    "/TradingPost": {
      "filePath": "TradingPost.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
